name: build

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build-pypi:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64

    steps:
    - name: Install dependencies
      run: |
        ls -alh /opt/python/cp*
        /opt/python/cp39-cp39/bin/python -m pip install numpy tqdm cython pytest scipy pylebedev matplotlib
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Build
      run: /opt/python/cp39*/bin/python setup.py bdist_wheel
    - name: Test
      run: |
        /opt/python/cp39-cp39/bin/python -m pip install numpy scipy nose pylebedev matplotlib networkx
        /opt/python/cp39-cp39/bin/pip install sphecerix --no-index -f ./dist
        /opt/python/cp39-cp39/bin/pytest --verbose tests
    - name: Archive wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist/sphecerix-*.whl

  build-anaconda:
    runs-on: ubuntu-latest
    container: conda/miniconda3

    steps:
      - name: Prepare build environment
        run: conda install -y conda-build
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build
        shell: bash -l {0}
        run: |
          conda build .
      - name: Archive packages
        uses: actions/upload-artifact@v3
        with:
          name: anaconda-packages
          path: /usr/local/conda-bld/noarch/sphecerix-*.tar.bz2